// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/anos.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxType int32

const (
	TxType_TX_TYPE_UNSPECIFIED TxType = 0
	TxType_TX_TYPE_SEND        TxType = 1
	TxType_TX_TYPE_RECEIVE     TxType = 2
)

// Enum value maps for TxType.
var (
	TxType_name = map[int32]string{
		0: "TX_TYPE_UNSPECIFIED",
		1: "TX_TYPE_SEND",
		2: "TX_TYPE_RECEIVE",
	}
	TxType_value = map[string]int32{
		"TX_TYPE_UNSPECIFIED": 0,
		"TX_TYPE_SEND":        1,
		"TX_TYPE_RECEIVE":     2,
	}
)

func (x TxType) Enum() *TxType {
	p := new(TxType)
	*p = x
	return p
}

func (x TxType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TxType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_anos_proto_enumTypes[0].Descriptor()
}

func (TxType) Type() protoreflect.EnumType {
	return &file_proto_anos_proto_enumTypes[0]
}

func (x TxType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TxType.Descriptor instead.
func (TxType) EnumDescriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{0}
}

type Hash32 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	V             []byte                 `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hash32) Reset() {
	*x = Hash32{}
	mi := &file_proto_anos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hash32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hash32) ProtoMessage() {}

func (x *Hash32) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hash32.ProtoReflect.Descriptor instead.
func (*Hash32) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{0}
}

func (x *Hash32) GetV() []byte {
	if x != nil {
		return x.V
	}
	return nil
}

type Sig64 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	V             []byte                 `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sig64) Reset() {
	*x = Sig64{}
	mi := &file_proto_anos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sig64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sig64) ProtoMessage() {}

func (x *Sig64) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sig64.ProtoReflect.Descriptor instead.
func (*Sig64) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{1}
}

func (x *Sig64) GetV() []byte {
	if x != nil {
		return x.V
	}
	return nil
}

type Pub32 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	V             []byte                 `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pub32) Reset() {
	*x = Pub32{}
	mi := &file_proto_anos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pub32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pub32) ProtoMessage() {}

func (x *Pub32) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pub32.ProtoReflect.Descriptor instead.
func (*Pub32) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{2}
}

func (x *Pub32) GetV() []byte {
	if x != nil {
		return x.V
	}
	return nil
}

// AccountId is the ed25519 public key bytes for v1 prototype.
type AccountId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	V             []byte                 `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountId) Reset() {
	*x = AccountId{}
	mi := &file_proto_anos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountId) ProtoMessage() {}

func (x *AccountId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountId.ProtoReflect.Descriptor instead.
func (*AccountId) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{3}
}

func (x *AccountId) GetV() []byte {
	if x != nil {
		return x.V
	}
	return nil
}

type TxBodySend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            *AccountId             `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Fee           uint64                 `protobuf:"varint,3,opt,name=fee,proto3" json:"fee,omitempty"`
	ReceivableId  *Hash32                `protobuf:"bytes,4,opt,name=receivable_id,json=receivableId,proto3" json:"receivable_id,omitempty"` // deterministically derived from txid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxBodySend) Reset() {
	*x = TxBodySend{}
	mi := &file_proto_anos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxBodySend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxBodySend) ProtoMessage() {}

func (x *TxBodySend) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxBodySend.ProtoReflect.Descriptor instead.
func (*TxBodySend) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{4}
}

func (x *TxBodySend) GetTo() *AccountId {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *TxBodySend) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TxBodySend) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *TxBodySend) GetReceivableId() *Hash32 {
	if x != nil {
		return x.ReceivableId
	}
	return nil
}

type TxBodyReceive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceivableId  *Hash32                `protobuf:"bytes,1,opt,name=receivable_id,json=receivableId,proto3" json:"receivable_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxBodyReceive) Reset() {
	*x = TxBodyReceive{}
	mi := &file_proto_anos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxBodyReceive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxBodyReceive) ProtoMessage() {}

func (x *TxBodyReceive) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxBodyReceive.ProtoReflect.Descriptor instead.
func (*TxBodyReceive) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{5}
}

func (x *TxBodyReceive) GetReceivableId() *Hash32 {
	if x != nil {
		return x.ReceivableId
	}
	return nil
}

// Canonical bytes-to-sign for a transaction.
// Rule: signature = Ed25519( SHA256( serialize(TxSignable) ) )
type TxSignable struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Type    TxType                 `protobuf:"varint,1,opt,name=type,proto3,enum=anos.v2.TxType" json:"type,omitempty"`
	Account *AccountId             `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"` // the account chain being extended
	Prev    *Hash32                `protobuf:"bytes,3,opt,name=prev,proto3" json:"prev,omitempty"`       // previous tx hash (zero/empty means genesis head)
	Seq     uint64                 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`        // monotonic per-account sequence
	// Types that are valid to be assigned to Body:
	//
	//	*TxSignable_Send
	//	*TxSignable_Receive
	Body          isTxSignable_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxSignable) Reset() {
	*x = TxSignable{}
	mi := &file_proto_anos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxSignable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxSignable) ProtoMessage() {}

func (x *TxSignable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxSignable.ProtoReflect.Descriptor instead.
func (*TxSignable) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{6}
}

func (x *TxSignable) GetType() TxType {
	if x != nil {
		return x.Type
	}
	return TxType_TX_TYPE_UNSPECIFIED
}

func (x *TxSignable) GetAccount() *AccountId {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *TxSignable) GetPrev() *Hash32 {
	if x != nil {
		return x.Prev
	}
	return nil
}

func (x *TxSignable) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *TxSignable) GetBody() isTxSignable_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *TxSignable) GetSend() *TxBodySend {
	if x != nil {
		if x, ok := x.Body.(*TxSignable_Send); ok {
			return x.Send
		}
	}
	return nil
}

func (x *TxSignable) GetReceive() *TxBodyReceive {
	if x != nil {
		if x, ok := x.Body.(*TxSignable_Receive); ok {
			return x.Receive
		}
	}
	return nil
}

type isTxSignable_Body interface {
	isTxSignable_Body()
}

type TxSignable_Send struct {
	Send *TxBodySend `protobuf:"bytes,10,opt,name=send,proto3,oneof"`
}

type TxSignable_Receive struct {
	Receive *TxBodyReceive `protobuf:"bytes,11,opt,name=receive,proto3,oneof"`
}

func (*TxSignable_Send) isTxSignable_Body() {}

func (*TxSignable_Receive) isTxSignable_Body() {}

type Tx struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Type    TxType                 `protobuf:"varint,1,opt,name=type,proto3,enum=anos.v2.TxType" json:"type,omitempty"`
	Account *AccountId             `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"` // the account chain being extended
	Prev    *Hash32                `protobuf:"bytes,3,opt,name=prev,proto3" json:"prev,omitempty"`       // previous tx hash (zero/empty means genesis head)
	Seq     uint64                 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`        // monotonic per-account sequence
	// Types that are valid to be assigned to Body:
	//
	//	*Tx_Send
	//	*Tx_Receive
	Body          isTx_Body `protobuf_oneof:"body"`
	Sig           *Sig64    `protobuf:"bytes,20,opt,name=sig,proto3" json:"sig,omitempty"` // signature over TxSignable canonical bytes (see above)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tx) Reset() {
	*x = Tx{}
	mi := &file_proto_anos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tx) ProtoMessage() {}

func (x *Tx) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tx.ProtoReflect.Descriptor instead.
func (*Tx) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{7}
}

func (x *Tx) GetType() TxType {
	if x != nil {
		return x.Type
	}
	return TxType_TX_TYPE_UNSPECIFIED
}

func (x *Tx) GetAccount() *AccountId {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *Tx) GetPrev() *Hash32 {
	if x != nil {
		return x.Prev
	}
	return nil
}

func (x *Tx) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Tx) GetBody() isTx_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Tx) GetSend() *TxBodySend {
	if x != nil {
		if x, ok := x.Body.(*Tx_Send); ok {
			return x.Send
		}
	}
	return nil
}

func (x *Tx) GetReceive() *TxBodyReceive {
	if x != nil {
		if x, ok := x.Body.(*Tx_Receive); ok {
			return x.Receive
		}
	}
	return nil
}

func (x *Tx) GetSig() *Sig64 {
	if x != nil {
		return x.Sig
	}
	return nil
}

type isTx_Body interface {
	isTx_Body()
}

type Tx_Send struct {
	Send *TxBodySend `protobuf:"bytes,10,opt,name=send,proto3,oneof"`
}

type Tx_Receive struct {
	Receive *TxBodyReceive `protobuf:"bytes,11,opt,name=receive,proto3,oneof"`
}

func (*Tx_Send) isTx_Body() {}

func (*Tx_Receive) isTx_Body() {}

type Receivable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *Hash32                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	From          *AccountId             `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            *AccountId             `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Amount        uint64                 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Fee           uint64                 `protobuf:"varint,5,opt,name=fee,proto3" json:"fee,omitempty"`
	CreatedByTx   *Hash32                `protobuf:"bytes,6,opt,name=created_by_tx,json=createdByTx,proto3" json:"created_by_tx,omitempty"`
	Claimed       bool                   `protobuf:"varint,7,opt,name=claimed,proto3" json:"claimed,omitempty"`
	ClaimedByTx   *Hash32                `protobuf:"bytes,8,opt,name=claimed_by_tx,json=claimedByTx,proto3" json:"claimed_by_tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receivable) Reset() {
	*x = Receivable{}
	mi := &file_proto_anos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receivable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receivable) ProtoMessage() {}

func (x *Receivable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receivable.ProtoReflect.Descriptor instead.
func (*Receivable) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{8}
}

func (x *Receivable) GetId() *Hash32 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Receivable) GetFrom() *AccountId {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Receivable) GetTo() *AccountId {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Receivable) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Receivable) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *Receivable) GetCreatedByTx() *Hash32 {
	if x != nil {
		return x.CreatedByTx
	}
	return nil
}

func (x *Receivable) GetClaimed() bool {
	if x != nil {
		return x.Claimed
	}
	return false
}

func (x *Receivable) GetClaimedByTx() *Hash32 {
	if x != nil {
		return x.ClaimedByTx
	}
	return nil
}

type EpochRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	AcceptedTxs   []*Hash32              `protobuf:"bytes,2,rep,name=accepted_txs,json=acceptedTxs,proto3" json:"accepted_txs,omitempty"`
	StateRoot     *Hash32                `protobuf:"bytes,3,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	PrevEpochHash *Hash32                `protobuf:"bytes,4,opt,name=prev_epoch_hash,json=prevEpochHash,proto3" json:"prev_epoch_hash,omitempty"` // hash-chain epochs for audit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpochRecord) Reset() {
	*x = EpochRecord{}
	mi := &file_proto_anos_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpochRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochRecord) ProtoMessage() {}

func (x *EpochRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpochRecord.ProtoReflect.Descriptor instead.
func (*EpochRecord) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{9}
}

func (x *EpochRecord) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *EpochRecord) GetAcceptedTxs() []*Hash32 {
	if x != nil {
		return x.AcceptedTxs
	}
	return nil
}

func (x *EpochRecord) GetStateRoot() *Hash32 {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *EpochRecord) GetPrevEpochHash() *Hash32 {
	if x != nil {
		return x.PrevEpochHash
	}
	return nil
}

// Generic error for API responses.
type ApiError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // HTTP-ish or app-specific code (e.g., 400, 403, 500)
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // human-readable summary
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`   // optional extra info (stack, debug, etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiError) Reset() {
	*x = ApiError{}
	mi := &file_proto_anos_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiError) ProtoMessage() {}

func (x *ApiError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiError.ProtoReflect.Descriptor instead.
func (*ApiError) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{10}
}

func (x *ApiError) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ApiError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiError) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// /submit
type SubmitTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tx            *Tx                    `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTxRequest) Reset() {
	*x = SubmitTxRequest{}
	mi := &file_proto_anos_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTxRequest) ProtoMessage() {}

func (x *SubmitTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTxRequest.ProtoReflect.Descriptor instead.
func (*SubmitTxRequest) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{11}
}

func (x *SubmitTxRequest) GetTx() *Tx {
	if x != nil {
		return x.Tx
	}
	return nil
}

type SubmitTxResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ok    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// Optional: txid as computed by validators (or client) for display/debug.
	Txid *Hash32 `protobuf:"bytes,2,opt,name=txid,proto3" json:"txid,omitempty"`
	// If ok=false, error is set.
	Error         *ApiError `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTxResponse) Reset() {
	*x = SubmitTxResponse{}
	mi := &file_proto_anos_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTxResponse) ProtoMessage() {}

func (x *SubmitTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTxResponse.ProtoReflect.Descriptor instead.
func (*SubmitTxResponse) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{12}
}

func (x *SubmitTxResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SubmitTxResponse) GetTxid() *Hash32 {
	if x != nil {
		return x.Txid
	}
	return nil
}

func (x *SubmitTxResponse) GetError() *ApiError {
	if x != nil {
		return x.Error
	}
	return nil
}

// /account
type AccountState struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Account *AccountId             `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// Current head tx hash (zero/empty means genesis head)
	Head          *Hash32 `protobuf:"bytes,2,opt,name=head,proto3" json:"head,omitempty"`
	Balance       uint64  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Seq           uint64  `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountState) Reset() {
	*x = AccountState{}
	mi := &file_proto_anos_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountState) ProtoMessage() {}

func (x *AccountState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountState.ProtoReflect.Descriptor instead.
func (*AccountState) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{13}
}

func (x *AccountState) GetAccount() *AccountId {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *AccountState) GetHead() *Hash32 {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *AccountState) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *AccountState) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *AccountId             `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_proto_anos_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{14}
}

func (x *GetAccountRequest) GetAccount() *AccountId {
	if x != nil {
		return x.Account
	}
	return nil
}

type GetAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	State         *AccountState          `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Error         *ApiError              `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_proto_anos_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{15}
}

func (x *GetAccountResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GetAccountResponse) GetState() *AccountState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *GetAccountResponse) GetError() *ApiError {
	if x != nil {
		return x.Error
	}
	return nil
}

// /receivables
type ListReceivablesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Account        *AccountId             `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`                                      // list receivables destined to this account
	IncludeClaimed bool                   `protobuf:"varint,2,opt,name=include_claimed,json=includeClaimed,proto3" json:"include_claimed,omitempty"` // default false
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListReceivablesRequest) Reset() {
	*x = ListReceivablesRequest{}
	mi := &file_proto_anos_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReceivablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReceivablesRequest) ProtoMessage() {}

func (x *ListReceivablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReceivablesRequest.ProtoReflect.Descriptor instead.
func (*ListReceivablesRequest) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{16}
}

func (x *ListReceivablesRequest) GetAccount() *AccountId {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *ListReceivablesRequest) GetIncludeClaimed() bool {
	if x != nil {
		return x.IncludeClaimed
	}
	return false
}

type ListReceivablesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Receivables   []*Receivable          `protobuf:"bytes,2,rep,name=receivables,proto3" json:"receivables,omitempty"`
	Error         *ApiError              `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReceivablesResponse) Reset() {
	*x = ListReceivablesResponse{}
	mi := &file_proto_anos_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReceivablesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReceivablesResponse) ProtoMessage() {}

func (x *ListReceivablesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReceivablesResponse.ProtoReflect.Descriptor instead.
func (*ListReceivablesResponse) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{17}
}

func (x *ListReceivablesResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ListReceivablesResponse) GetReceivables() []*Receivable {
	if x != nil {
		return x.Receivables
	}
	return nil
}

func (x *ListReceivablesResponse) GetError() *ApiError {
	if x != nil {
		return x.Error
	}
	return nil
}

// Your code currently uses Sig64 to carry DER P-256 signatures (variable length).
// Keep compatibility but add an explicit type for clarity going forward.
type SigDER struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	V             []byte                 `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigDER) Reset() {
	*x = SigDER{}
	mi := &file_proto_anos_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigDER) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigDER) ProtoMessage() {}

func (x *SigDER) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigDER.ProtoReflect.Descriptor instead.
func (*SigDER) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{18}
}

func (x *SigDER) GetV() []byte {
	if x != nil {
		return x.V
	}
	return nil
}

type TxInv struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"` // sender's current epoch (informational)
	From          *Pub32                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`    // validator_id (your code uses Pub32 but expects 33 bytes)
	Txid          []*Hash32              `protobuf:"bytes,3,rep,name=txid,proto3" json:"txid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxInv) Reset() {
	*x = TxInv{}
	mi := &file_proto_anos_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxInv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxInv) ProtoMessage() {}

func (x *TxInv) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxInv.ProtoReflect.Descriptor instead.
func (*TxInv) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{19}
}

func (x *TxInv) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *TxInv) GetFrom() *Pub32 {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *TxInv) GetTxid() []*Hash32 {
	if x != nil {
		return x.Txid
	}
	return nil
}

type TxWant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	From          *Pub32                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Txid          []*Hash32              `protobuf:"bytes,3,rep,name=txid,proto3" json:"txid,omitempty"` // which txids receiver wants bytes for
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxWant) Reset() {
	*x = TxWant{}
	mi := &file_proto_anos_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxWant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxWant) ProtoMessage() {}

func (x *TxWant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxWant.ProtoReflect.Descriptor instead.
func (*TxWant) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{20}
}

func (x *TxWant) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *TxWant) GetFrom() *Pub32 {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *TxWant) GetTxid() []*Hash32 {
	if x != nil {
		return x.Txid
	}
	return nil
}

type TxPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	From          *Pub32                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Tx            []*Tx                  `protobuf:"bytes,3,rep,name=tx,proto3" json:"tx,omitempty"` // full Tx objects (protobuf)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxPush) Reset() {
	*x = TxPush{}
	mi := &file_proto_anos_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxPush) ProtoMessage() {}

func (x *TxPush) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxPush.ProtoReflect.Descriptor instead.
func (*TxPush) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{21}
}

func (x *TxPush) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *TxPush) GetFrom() *Pub32 {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *TxPush) GetTx() []*Tx {
	if x != nil {
		return x.Tx
	}
	return nil
}

// --- Candidate list v2 (txids only; votes) ---
// list_hash = SHA256(concat(sorted txid bytes))
type CandidateListV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Proposer      *Pub32                 `protobuf:"bytes,2,opt,name=proposer,proto3" json:"proposer,omitempty"` // validator_id
	Txid          []*Hash32              `protobuf:"bytes,3,rep,name=txid,proto3" json:"txid,omitempty"`         // txids only (sorted by sender)
	ListHash      *Hash32                `protobuf:"bytes,4,opt,name=list_hash,json=listHash,proto3" json:"list_hash,omitempty"`
	Sig           *SigDER                `protobuf:"bytes,5,opt,name=sig,proto3" json:"sig,omitempty"` // signature over digest(epoch, proposer, list_hash)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandidateListV2) Reset() {
	*x = CandidateListV2{}
	mi := &file_proto_anos_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateListV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateListV2) ProtoMessage() {}

func (x *CandidateListV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateListV2.ProtoReflect.Descriptor instead.
func (*CandidateListV2) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{22}
}

func (x *CandidateListV2) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *CandidateListV2) GetProposer() *Pub32 {
	if x != nil {
		return x.Proposer
	}
	return nil
}

func (x *CandidateListV2) GetTxid() []*Hash32 {
	if x != nil {
		return x.Txid
	}
	return nil
}

func (x *CandidateListV2) GetListHash() *Hash32 {
	if x != nil {
		return x.ListHash
	}
	return nil
}

func (x *CandidateListV2) GetSig() *SigDER {
	if x != nil {
		return x.Sig
	}
	return nil
}

// --- Epoch finalization (checkpoint anchor for resync) ---
// accepted_txids_hash = SHA256(concat(sorted accepted txid bytes))
// frontiers_root      = SHA256(concat(sorted (account_id||head_hash) bytes)) for this epoch snapshot
type EpochFinalization struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Epoch             uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	AcceptedTxidsHash *Hash32                `protobuf:"bytes,2,opt,name=accepted_txids_hash,json=acceptedTxidsHash,proto3" json:"accepted_txids_hash,omitempty"`
	FrontiersRoot     *Hash32                `protobuf:"bytes,3,opt,name=frontiers_root,json=frontiersRoot,proto3" json:"frontiers_root,omitempty"`
	Signer            *Pub32                 `protobuf:"bytes,4,opt,name=signer,proto3" json:"signer,omitempty"` // validator_id
	Sig               *SigDER                `protobuf:"bytes,5,opt,name=sig,proto3" json:"sig,omitempty"`       // signature over digest(epoch, accepted_txids_hash, frontiers_root)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EpochFinalization) Reset() {
	*x = EpochFinalization{}
	mi := &file_proto_anos_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpochFinalization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochFinalization) ProtoMessage() {}

func (x *EpochFinalization) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpochFinalization.ProtoReflect.Descriptor instead.
func (*EpochFinalization) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{23}
}

func (x *EpochFinalization) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *EpochFinalization) GetAcceptedTxidsHash() *Hash32 {
	if x != nil {
		return x.AcceptedTxidsHash
	}
	return nil
}

func (x *EpochFinalization) GetFrontiersRoot() *Hash32 {
	if x != nil {
		return x.FrontiersRoot
	}
	return nil
}

func (x *EpochFinalization) GetSigner() *Pub32 {
	if x != nil {
		return x.Signer
	}
	return nil
}

func (x *EpochFinalization) GetSig() *SigDER {
	if x != nil {
		return x.Sig
	}
	return nil
}

type SyncLatestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncLatestRequest) Reset() {
	*x = SyncLatestRequest{}
	mi := &file_proto_anos_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncLatestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncLatestRequest) ProtoMessage() {}

func (x *SyncLatestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncLatestRequest.ProtoReflect.Descriptor instead.
func (*SyncLatestRequest) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{24}
}

type SyncLatestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LatestEpoch   uint64                 `protobuf:"varint,1,opt,name=latest_epoch,json=latestEpoch,proto3" json:"latest_epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncLatestResponse) Reset() {
	*x = SyncLatestResponse{}
	mi := &file_proto_anos_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncLatestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncLatestResponse) ProtoMessage() {}

func (x *SyncLatestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncLatestResponse.ProtoReflect.Descriptor instead.
func (*SyncLatestResponse) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{25}
}

func (x *SyncLatestResponse) GetLatestEpoch() uint64 {
	if x != nil {
		return x.LatestEpoch
	}
	return 0
}

type SyncFinalizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncFinalizationRequest) Reset() {
	*x = SyncFinalizationRequest{}
	mi := &file_proto_anos_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFinalizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFinalizationRequest) ProtoMessage() {}

func (x *SyncFinalizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFinalizationRequest.ProtoReflect.Descriptor instead.
func (*SyncFinalizationRequest) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{26}
}

func (x *SyncFinalizationRequest) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type SyncFinalizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Finalizations []*EpochFinalization   `protobuf:"bytes,1,rep,name=finalizations,proto3" json:"finalizations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncFinalizationResponse) Reset() {
	*x = SyncFinalizationResponse{}
	mi := &file_proto_anos_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFinalizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFinalizationResponse) ProtoMessage() {}

func (x *SyncFinalizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFinalizationResponse.ProtoReflect.Descriptor instead.
func (*SyncFinalizationResponse) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{27}
}

func (x *SyncFinalizationResponse) GetFinalizations() []*EpochFinalization {
	if x != nil {
		return x.Finalizations
	}
	return nil
}

type FrontierEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *AccountId             `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"` // 32 bytes
	Head          *Hash32                `protobuf:"bytes,2,opt,name=head,proto3" json:"head,omitempty"`       // 32 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrontierEntry) Reset() {
	*x = FrontierEntry{}
	mi := &file_proto_anos_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontierEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontierEntry) ProtoMessage() {}

func (x *FrontierEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontierEntry.ProtoReflect.Descriptor instead.
func (*FrontierEntry) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{28}
}

func (x *FrontierEntry) GetAccount() *AccountId {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *FrontierEntry) GetHead() *Hash32 {
	if x != nil {
		return x.Head
	}
	return nil
}

type SyncFrontiersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Cursor        *AccountId             `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"` // optional; empty means start
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncFrontiersRequest) Reset() {
	*x = SyncFrontiersRequest{}
	mi := &file_proto_anos_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFrontiersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFrontiersRequest) ProtoMessage() {}

func (x *SyncFrontiersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFrontiersRequest.ProtoReflect.Descriptor instead.
func (*SyncFrontiersRequest) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{29}
}

func (x *SyncFrontiersRequest) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *SyncFrontiersRequest) GetCursor() *AccountId {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *SyncFrontiersRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SyncFrontiersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Entries       []*FrontierEntry       `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	NextCursor    *AccountId             `protobuf:"bytes,3,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"` // empty when done
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncFrontiersResponse) Reset() {
	*x = SyncFrontiersResponse{}
	mi := &file_proto_anos_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFrontiersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFrontiersResponse) ProtoMessage() {}

func (x *SyncFrontiersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFrontiersResponse.ProtoReflect.Descriptor instead.
func (*SyncFrontiersResponse) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{30}
}

func (x *SyncFrontiersResponse) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *SyncFrontiersResponse) GetEntries() []*FrontierEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *SyncFrontiersResponse) GetNextCursor() *AccountId {
	if x != nil {
		return x.NextCursor
	}
	return nil
}

type SyncChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *AccountId             `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	TargetHead    *Hash32                `protobuf:"bytes,2,opt,name=target_head,json=targetHead,proto3" json:"target_head,omitempty"`
	Have          *Hash32                `protobuf:"bytes,3,opt,name=have,proto3" json:"have,omitempty"` // optional; empty means "no have"
	MaxBlocks     uint32                 `protobuf:"varint,4,opt,name=max_blocks,json=maxBlocks,proto3" json:"max_blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncChainRequest) Reset() {
	*x = SyncChainRequest{}
	mi := &file_proto_anos_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncChainRequest) ProtoMessage() {}

func (x *SyncChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncChainRequest.ProtoReflect.Descriptor instead.
func (*SyncChainRequest) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{31}
}

func (x *SyncChainRequest) GetAccount() *AccountId {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *SyncChainRequest) GetTargetHead() *Hash32 {
	if x != nil {
		return x.TargetHead
	}
	return nil
}

func (x *SyncChainRequest) GetHave() *Hash32 {
	if x != nil {
		return x.Have
	}
	return nil
}

func (x *SyncChainRequest) GetMaxBlocks() uint32 {
	if x != nil {
		return x.MaxBlocks
	}
	return 0
}

type SyncChainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tx            []*Tx                  `protobuf:"bytes,1,rep,name=tx,proto3" json:"tx,omitempty"` // from target head backwards (head-first order)
	ReachedHave   bool                   `protobuf:"varint,2,opt,name=reached_have,json=reachedHave,proto3" json:"reached_have,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncChainResponse) Reset() {
	*x = SyncChainResponse{}
	mi := &file_proto_anos_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncChainResponse) ProtoMessage() {}

func (x *SyncChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncChainResponse.ProtoReflect.Descriptor instead.
func (*SyncChainResponse) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{32}
}

func (x *SyncChainResponse) GetTx() []*Tx {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *SyncChainResponse) GetReachedHave() bool {
	if x != nil {
		return x.ReachedHave
	}
	return false
}

var File_proto_anos_proto protoreflect.FileDescriptor

const file_proto_anos_proto_rawDesc = "" +
	"\n" +
	"\x10proto/anos.proto\x12\aanos.v2\"\x16\n" +
	"\x06Hash32\x12\f\n" +
	"\x01v\x18\x01 \x01(\fR\x01v\"\x15\n" +
	"\x05Sig64\x12\f\n" +
	"\x01v\x18\x01 \x01(\fR\x01v\"\x15\n" +
	"\x05Pub32\x12\f\n" +
	"\x01v\x18\x01 \x01(\fR\x01v\"\x19\n" +
	"\tAccountId\x12\f\n" +
	"\x01v\x18\x01 \x01(\fR\x01v\"\x90\x01\n" +
	"\n" +
	"TxBodySend\x12\"\n" +
	"\x02to\x18\x01 \x01(\v2\x12.anos.v2.AccountIdR\x02to\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x12\x10\n" +
	"\x03fee\x18\x03 \x01(\x04R\x03fee\x124\n" +
	"\rreceivable_id\x18\x04 \x01(\v2\x0f.anos.v2.Hash32R\freceivableId\"E\n" +
	"\rTxBodyReceive\x124\n" +
	"\rreceivable_id\x18\x01 \x01(\v2\x0f.anos.v2.Hash32R\freceivableId\"\xfd\x01\n" +
	"\n" +
	"TxSignable\x12#\n" +
	"\x04type\x18\x01 \x01(\x0e2\x0f.anos.v2.TxTypeR\x04type\x12,\n" +
	"\aaccount\x18\x02 \x01(\v2\x12.anos.v2.AccountIdR\aaccount\x12#\n" +
	"\x04prev\x18\x03 \x01(\v2\x0f.anos.v2.Hash32R\x04prev\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\x12)\n" +
	"\x04send\x18\n" +
	" \x01(\v2\x13.anos.v2.TxBodySendH\x00R\x04send\x122\n" +
	"\areceive\x18\v \x01(\v2\x16.anos.v2.TxBodyReceiveH\x00R\areceiveB\x06\n" +
	"\x04body\"\x97\x02\n" +
	"\x02Tx\x12#\n" +
	"\x04type\x18\x01 \x01(\x0e2\x0f.anos.v2.TxTypeR\x04type\x12,\n" +
	"\aaccount\x18\x02 \x01(\v2\x12.anos.v2.AccountIdR\aaccount\x12#\n" +
	"\x04prev\x18\x03 \x01(\v2\x0f.anos.v2.Hash32R\x04prev\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\x12)\n" +
	"\x04send\x18\n" +
	" \x01(\v2\x13.anos.v2.TxBodySendH\x00R\x04send\x122\n" +
	"\areceive\x18\v \x01(\v2\x16.anos.v2.TxBodyReceiveH\x00R\areceive\x12 \n" +
	"\x03sig\x18\x14 \x01(\v2\x0e.anos.v2.Sig64R\x03sigB\x06\n" +
	"\x04body\"\xa7\x02\n" +
	"\n" +
	"Receivable\x12\x1f\n" +
	"\x02id\x18\x01 \x01(\v2\x0f.anos.v2.Hash32R\x02id\x12&\n" +
	"\x04from\x18\x02 \x01(\v2\x12.anos.v2.AccountIdR\x04from\x12\"\n" +
	"\x02to\x18\x03 \x01(\v2\x12.anos.v2.AccountIdR\x02to\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x04R\x06amount\x12\x10\n" +
	"\x03fee\x18\x05 \x01(\x04R\x03fee\x123\n" +
	"\rcreated_by_tx\x18\x06 \x01(\v2\x0f.anos.v2.Hash32R\vcreatedByTx\x12\x18\n" +
	"\aclaimed\x18\a \x01(\bR\aclaimed\x123\n" +
	"\rclaimed_by_tx\x18\b \x01(\v2\x0f.anos.v2.Hash32R\vclaimedByTx\"\xc0\x01\n" +
	"\vEpochRecord\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x122\n" +
	"\faccepted_txs\x18\x02 \x03(\v2\x0f.anos.v2.Hash32R\vacceptedTxs\x12.\n" +
	"\n" +
	"state_root\x18\x03 \x01(\v2\x0f.anos.v2.Hash32R\tstateRoot\x127\n" +
	"\x0fprev_epoch_hash\x18\x04 \x01(\v2\x0f.anos.v2.Hash32R\rprevEpochHash\"P\n" +
	"\bApiError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\".\n" +
	"\x0fSubmitTxRequest\x12\x1b\n" +
	"\x02tx\x18\x01 \x01(\v2\v.anos.v2.TxR\x02tx\"p\n" +
	"\x10SubmitTxResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12#\n" +
	"\x04txid\x18\x02 \x01(\v2\x0f.anos.v2.Hash32R\x04txid\x12'\n" +
	"\x05error\x18\x03 \x01(\v2\x11.anos.v2.ApiErrorR\x05error\"\x8d\x01\n" +
	"\fAccountState\x12,\n" +
	"\aaccount\x18\x01 \x01(\v2\x12.anos.v2.AccountIdR\aaccount\x12#\n" +
	"\x04head\x18\x02 \x01(\v2\x0f.anos.v2.Hash32R\x04head\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x04R\abalance\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\"A\n" +
	"\x11GetAccountRequest\x12,\n" +
	"\aaccount\x18\x01 \x01(\v2\x12.anos.v2.AccountIdR\aaccount\"z\n" +
	"\x12GetAccountResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12+\n" +
	"\x05state\x18\x02 \x01(\v2\x15.anos.v2.AccountStateR\x05state\x12'\n" +
	"\x05error\x18\x03 \x01(\v2\x11.anos.v2.ApiErrorR\x05error\"o\n" +
	"\x16ListReceivablesRequest\x12,\n" +
	"\aaccount\x18\x01 \x01(\v2\x12.anos.v2.AccountIdR\aaccount\x12'\n" +
	"\x0finclude_claimed\x18\x02 \x01(\bR\x0eincludeClaimed\"\x89\x01\n" +
	"\x17ListReceivablesResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x125\n" +
	"\vreceivables\x18\x02 \x03(\v2\x13.anos.v2.ReceivableR\vreceivables\x12'\n" +
	"\x05error\x18\x03 \x01(\v2\x11.anos.v2.ApiErrorR\x05error\"\x16\n" +
	"\x06SigDER\x12\f\n" +
	"\x01v\x18\x01 \x01(\fR\x01v\"f\n" +
	"\x05TxInv\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12\"\n" +
	"\x04from\x18\x02 \x01(\v2\x0e.anos.v2.Pub32R\x04from\x12#\n" +
	"\x04txid\x18\x03 \x03(\v2\x0f.anos.v2.Hash32R\x04txid\"g\n" +
	"\x06TxWant\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12\"\n" +
	"\x04from\x18\x02 \x01(\v2\x0e.anos.v2.Pub32R\x04from\x12#\n" +
	"\x04txid\x18\x03 \x03(\v2\x0f.anos.v2.Hash32R\x04txid\"_\n" +
	"\x06TxPush\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12\"\n" +
	"\x04from\x18\x02 \x01(\v2\x0e.anos.v2.Pub32R\x04from\x12\x1b\n" +
	"\x02tx\x18\x03 \x03(\v2\v.anos.v2.TxR\x02tx\"\xc9\x01\n" +
	"\x0fCandidateListV2\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12*\n" +
	"\bproposer\x18\x02 \x01(\v2\x0e.anos.v2.Pub32R\bproposer\x12#\n" +
	"\x04txid\x18\x03 \x03(\v2\x0f.anos.v2.Hash32R\x04txid\x12,\n" +
	"\tlist_hash\x18\x04 \x01(\v2\x0f.anos.v2.Hash32R\blistHash\x12!\n" +
	"\x03sig\x18\x05 \x01(\v2\x0f.anos.v2.SigDERR\x03sig\"\xed\x01\n" +
	"\x11EpochFinalization\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12?\n" +
	"\x13accepted_txids_hash\x18\x02 \x01(\v2\x0f.anos.v2.Hash32R\x11acceptedTxidsHash\x126\n" +
	"\x0efrontiers_root\x18\x03 \x01(\v2\x0f.anos.v2.Hash32R\rfrontiersRoot\x12&\n" +
	"\x06signer\x18\x04 \x01(\v2\x0e.anos.v2.Pub32R\x06signer\x12!\n" +
	"\x03sig\x18\x05 \x01(\v2\x0f.anos.v2.SigDERR\x03sig\"\x13\n" +
	"\x11SyncLatestRequest\"7\n" +
	"\x12SyncLatestResponse\x12!\n" +
	"\flatest_epoch\x18\x01 \x01(\x04R\vlatestEpoch\"/\n" +
	"\x17SyncFinalizationRequest\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\"\\\n" +
	"\x18SyncFinalizationResponse\x12@\n" +
	"\rfinalizations\x18\x01 \x03(\v2\x1a.anos.v2.EpochFinalizationR\rfinalizations\"b\n" +
	"\rFrontierEntry\x12,\n" +
	"\aaccount\x18\x01 \x01(\v2\x12.anos.v2.AccountIdR\aaccount\x12#\n" +
	"\x04head\x18\x02 \x01(\v2\x0f.anos.v2.Hash32R\x04head\"n\n" +
	"\x14SyncFrontiersRequest\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12*\n" +
	"\x06cursor\x18\x02 \x01(\v2\x12.anos.v2.AccountIdR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"\x94\x01\n" +
	"\x15SyncFrontiersResponse\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x120\n" +
	"\aentries\x18\x02 \x03(\v2\x16.anos.v2.FrontierEntryR\aentries\x123\n" +
	"\vnext_cursor\x18\x03 \x01(\v2\x12.anos.v2.AccountIdR\n" +
	"nextCursor\"\xb6\x01\n" +
	"\x10SyncChainRequest\x12,\n" +
	"\aaccount\x18\x01 \x01(\v2\x12.anos.v2.AccountIdR\aaccount\x120\n" +
	"\vtarget_head\x18\x02 \x01(\v2\x0f.anos.v2.Hash32R\n" +
	"targetHead\x12#\n" +
	"\x04have\x18\x03 \x01(\v2\x0f.anos.v2.Hash32R\x04have\x12\x1d\n" +
	"\n" +
	"max_blocks\x18\x04 \x01(\rR\tmaxBlocks\"S\n" +
	"\x11SyncChainResponse\x12\x1b\n" +
	"\x02tx\x18\x01 \x03(\v2\v.anos.v2.TxR\x02tx\x12!\n" +
	"\freached_have\x18\x02 \x01(\bR\vreachedHave*H\n" +
	"\x06TxType\x12\x17\n" +
	"\x13TX_TYPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fTX_TYPE_SEND\x10\x01\x12\x13\n" +
	"\x0fTX_TYPE_RECEIVE\x10\x02B\x18Z\x16anos/internal/proto;pbb\x06proto3"

var (
	file_proto_anos_proto_rawDescOnce sync.Once
	file_proto_anos_proto_rawDescData []byte
)

func file_proto_anos_proto_rawDescGZIP() []byte {
	file_proto_anos_proto_rawDescOnce.Do(func() {
		file_proto_anos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_anos_proto_rawDesc), len(file_proto_anos_proto_rawDesc)))
	})
	return file_proto_anos_proto_rawDescData
}

var file_proto_anos_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_anos_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_proto_anos_proto_goTypes = []any{
	(TxType)(0),                      // 0: anos.v2.TxType
	(*Hash32)(nil),                   // 1: anos.v2.Hash32
	(*Sig64)(nil),                    // 2: anos.v2.Sig64
	(*Pub32)(nil),                    // 3: anos.v2.Pub32
	(*AccountId)(nil),                // 4: anos.v2.AccountId
	(*TxBodySend)(nil),               // 5: anos.v2.TxBodySend
	(*TxBodyReceive)(nil),            // 6: anos.v2.TxBodyReceive
	(*TxSignable)(nil),               // 7: anos.v2.TxSignable
	(*Tx)(nil),                       // 8: anos.v2.Tx
	(*Receivable)(nil),               // 9: anos.v2.Receivable
	(*EpochRecord)(nil),              // 10: anos.v2.EpochRecord
	(*ApiError)(nil),                 // 11: anos.v2.ApiError
	(*SubmitTxRequest)(nil),          // 12: anos.v2.SubmitTxRequest
	(*SubmitTxResponse)(nil),         // 13: anos.v2.SubmitTxResponse
	(*AccountState)(nil),             // 14: anos.v2.AccountState
	(*GetAccountRequest)(nil),        // 15: anos.v2.GetAccountRequest
	(*GetAccountResponse)(nil),       // 16: anos.v2.GetAccountResponse
	(*ListReceivablesRequest)(nil),   // 17: anos.v2.ListReceivablesRequest
	(*ListReceivablesResponse)(nil),  // 18: anos.v2.ListReceivablesResponse
	(*SigDER)(nil),                   // 19: anos.v2.SigDER
	(*TxInv)(nil),                    // 20: anos.v2.TxInv
	(*TxWant)(nil),                   // 21: anos.v2.TxWant
	(*TxPush)(nil),                   // 22: anos.v2.TxPush
	(*CandidateListV2)(nil),          // 23: anos.v2.CandidateListV2
	(*EpochFinalization)(nil),        // 24: anos.v2.EpochFinalization
	(*SyncLatestRequest)(nil),        // 25: anos.v2.SyncLatestRequest
	(*SyncLatestResponse)(nil),       // 26: anos.v2.SyncLatestResponse
	(*SyncFinalizationRequest)(nil),  // 27: anos.v2.SyncFinalizationRequest
	(*SyncFinalizationResponse)(nil), // 28: anos.v2.SyncFinalizationResponse
	(*FrontierEntry)(nil),            // 29: anos.v2.FrontierEntry
	(*SyncFrontiersRequest)(nil),     // 30: anos.v2.SyncFrontiersRequest
	(*SyncFrontiersResponse)(nil),    // 31: anos.v2.SyncFrontiersResponse
	(*SyncChainRequest)(nil),         // 32: anos.v2.SyncChainRequest
	(*SyncChainResponse)(nil),        // 33: anos.v2.SyncChainResponse
}
var file_proto_anos_proto_depIdxs = []int32{
	4,  // 0: anos.v2.TxBodySend.to:type_name -> anos.v2.AccountId
	1,  // 1: anos.v2.TxBodySend.receivable_id:type_name -> anos.v2.Hash32
	1,  // 2: anos.v2.TxBodyReceive.receivable_id:type_name -> anos.v2.Hash32
	0,  // 3: anos.v2.TxSignable.type:type_name -> anos.v2.TxType
	4,  // 4: anos.v2.TxSignable.account:type_name -> anos.v2.AccountId
	1,  // 5: anos.v2.TxSignable.prev:type_name -> anos.v2.Hash32
	5,  // 6: anos.v2.TxSignable.send:type_name -> anos.v2.TxBodySend
	6,  // 7: anos.v2.TxSignable.receive:type_name -> anos.v2.TxBodyReceive
	0,  // 8: anos.v2.Tx.type:type_name -> anos.v2.TxType
	4,  // 9: anos.v2.Tx.account:type_name -> anos.v2.AccountId
	1,  // 10: anos.v2.Tx.prev:type_name -> anos.v2.Hash32
	5,  // 11: anos.v2.Tx.send:type_name -> anos.v2.TxBodySend
	6,  // 12: anos.v2.Tx.receive:type_name -> anos.v2.TxBodyReceive
	2,  // 13: anos.v2.Tx.sig:type_name -> anos.v2.Sig64
	1,  // 14: anos.v2.Receivable.id:type_name -> anos.v2.Hash32
	4,  // 15: anos.v2.Receivable.from:type_name -> anos.v2.AccountId
	4,  // 16: anos.v2.Receivable.to:type_name -> anos.v2.AccountId
	1,  // 17: anos.v2.Receivable.created_by_tx:type_name -> anos.v2.Hash32
	1,  // 18: anos.v2.Receivable.claimed_by_tx:type_name -> anos.v2.Hash32
	1,  // 19: anos.v2.EpochRecord.accepted_txs:type_name -> anos.v2.Hash32
	1,  // 20: anos.v2.EpochRecord.state_root:type_name -> anos.v2.Hash32
	1,  // 21: anos.v2.EpochRecord.prev_epoch_hash:type_name -> anos.v2.Hash32
	8,  // 22: anos.v2.SubmitTxRequest.tx:type_name -> anos.v2.Tx
	1,  // 23: anos.v2.SubmitTxResponse.txid:type_name -> anos.v2.Hash32
	11, // 24: anos.v2.SubmitTxResponse.error:type_name -> anos.v2.ApiError
	4,  // 25: anos.v2.AccountState.account:type_name -> anos.v2.AccountId
	1,  // 26: anos.v2.AccountState.head:type_name -> anos.v2.Hash32
	4,  // 27: anos.v2.GetAccountRequest.account:type_name -> anos.v2.AccountId
	14, // 28: anos.v2.GetAccountResponse.state:type_name -> anos.v2.AccountState
	11, // 29: anos.v2.GetAccountResponse.error:type_name -> anos.v2.ApiError
	4,  // 30: anos.v2.ListReceivablesRequest.account:type_name -> anos.v2.AccountId
	9,  // 31: anos.v2.ListReceivablesResponse.receivables:type_name -> anos.v2.Receivable
	11, // 32: anos.v2.ListReceivablesResponse.error:type_name -> anos.v2.ApiError
	3,  // 33: anos.v2.TxInv.from:type_name -> anos.v2.Pub32
	1,  // 34: anos.v2.TxInv.txid:type_name -> anos.v2.Hash32
	3,  // 35: anos.v2.TxWant.from:type_name -> anos.v2.Pub32
	1,  // 36: anos.v2.TxWant.txid:type_name -> anos.v2.Hash32
	3,  // 37: anos.v2.TxPush.from:type_name -> anos.v2.Pub32
	8,  // 38: anos.v2.TxPush.tx:type_name -> anos.v2.Tx
	3,  // 39: anos.v2.CandidateListV2.proposer:type_name -> anos.v2.Pub32
	1,  // 40: anos.v2.CandidateListV2.txid:type_name -> anos.v2.Hash32
	1,  // 41: anos.v2.CandidateListV2.list_hash:type_name -> anos.v2.Hash32
	19, // 42: anos.v2.CandidateListV2.sig:type_name -> anos.v2.SigDER
	1,  // 43: anos.v2.EpochFinalization.accepted_txids_hash:type_name -> anos.v2.Hash32
	1,  // 44: anos.v2.EpochFinalization.frontiers_root:type_name -> anos.v2.Hash32
	3,  // 45: anos.v2.EpochFinalization.signer:type_name -> anos.v2.Pub32
	19, // 46: anos.v2.EpochFinalization.sig:type_name -> anos.v2.SigDER
	24, // 47: anos.v2.SyncFinalizationResponse.finalizations:type_name -> anos.v2.EpochFinalization
	4,  // 48: anos.v2.FrontierEntry.account:type_name -> anos.v2.AccountId
	1,  // 49: anos.v2.FrontierEntry.head:type_name -> anos.v2.Hash32
	4,  // 50: anos.v2.SyncFrontiersRequest.cursor:type_name -> anos.v2.AccountId
	29, // 51: anos.v2.SyncFrontiersResponse.entries:type_name -> anos.v2.FrontierEntry
	4,  // 52: anos.v2.SyncFrontiersResponse.next_cursor:type_name -> anos.v2.AccountId
	4,  // 53: anos.v2.SyncChainRequest.account:type_name -> anos.v2.AccountId
	1,  // 54: anos.v2.SyncChainRequest.target_head:type_name -> anos.v2.Hash32
	1,  // 55: anos.v2.SyncChainRequest.have:type_name -> anos.v2.Hash32
	8,  // 56: anos.v2.SyncChainResponse.tx:type_name -> anos.v2.Tx
	57, // [57:57] is the sub-list for method output_type
	57, // [57:57] is the sub-list for method input_type
	57, // [57:57] is the sub-list for extension type_name
	57, // [57:57] is the sub-list for extension extendee
	0,  // [0:57] is the sub-list for field type_name
}

func init() { file_proto_anos_proto_init() }
func file_proto_anos_proto_init() {
	if File_proto_anos_proto != nil {
		return
	}
	file_proto_anos_proto_msgTypes[6].OneofWrappers = []any{
		(*TxSignable_Send)(nil),
		(*TxSignable_Receive)(nil),
	}
	file_proto_anos_proto_msgTypes[7].OneofWrappers = []any{
		(*Tx_Send)(nil),
		(*Tx_Receive)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_anos_proto_rawDesc), len(file_proto_anos_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_anos_proto_goTypes,
		DependencyIndexes: file_proto_anos_proto_depIdxs,
		EnumInfos:         file_proto_anos_proto_enumTypes,
		MessageInfos:      file_proto_anos_proto_msgTypes,
	}.Build()
	File_proto_anos_proto = out.File
	file_proto_anos_proto_goTypes = nil
	file_proto_anos_proto_depIdxs = nil
}
