// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/anos.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxType int32

const (
	TxType_TX_TYPE_UNSPECIFIED TxType = 0
	TxType_TX_TYPE_SEND        TxType = 1
	TxType_TX_TYPE_RECEIVE     TxType = 2
)

// Enum value maps for TxType.
var (
	TxType_name = map[int32]string{
		0: "TX_TYPE_UNSPECIFIED",
		1: "TX_TYPE_SEND",
		2: "TX_TYPE_RECEIVE",
	}
	TxType_value = map[string]int32{
		"TX_TYPE_UNSPECIFIED": 0,
		"TX_TYPE_SEND":        1,
		"TX_TYPE_RECEIVE":     2,
	}
)

func (x TxType) Enum() *TxType {
	p := new(TxType)
	*p = x
	return p
}

func (x TxType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TxType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_anos_proto_enumTypes[0].Descriptor()
}

func (TxType) Type() protoreflect.EnumType {
	return &file_proto_anos_proto_enumTypes[0]
}

func (x TxType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TxType.Descriptor instead.
func (TxType) EnumDescriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{0}
}

type Hash32 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	V             []byte                 `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hash32) Reset() {
	*x = Hash32{}
	mi := &file_proto_anos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hash32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hash32) ProtoMessage() {}

func (x *Hash32) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hash32.ProtoReflect.Descriptor instead.
func (*Hash32) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{0}
}

func (x *Hash32) GetV() []byte {
	if x != nil {
		return x.V
	}
	return nil
}

type Sig64 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	V             []byte                 `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sig64) Reset() {
	*x = Sig64{}
	mi := &file_proto_anos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sig64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sig64) ProtoMessage() {}

func (x *Sig64) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sig64.ProtoReflect.Descriptor instead.
func (*Sig64) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{1}
}

func (x *Sig64) GetV() []byte {
	if x != nil {
		return x.V
	}
	return nil
}

type Pub32 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	V             []byte                 `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pub32) Reset() {
	*x = Pub32{}
	mi := &file_proto_anos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pub32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pub32) ProtoMessage() {}

func (x *Pub32) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pub32.ProtoReflect.Descriptor instead.
func (*Pub32) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{2}
}

func (x *Pub32) GetV() []byte {
	if x != nil {
		return x.V
	}
	return nil
}

// AccountId is the ed25519 public key bytes for v1 prototype.
type AccountId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	V             []byte                 `protobuf:"bytes,1,opt,name=v,proto3" json:"v,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountId) Reset() {
	*x = AccountId{}
	mi := &file_proto_anos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountId) ProtoMessage() {}

func (x *AccountId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountId.ProtoReflect.Descriptor instead.
func (*AccountId) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{3}
}

func (x *AccountId) GetV() []byte {
	if x != nil {
		return x.V
	}
	return nil
}

type TxBodySend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            *AccountId             `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Fee           uint64                 `protobuf:"varint,3,opt,name=fee,proto3" json:"fee,omitempty"`
	ReceivableId  *Hash32                `protobuf:"bytes,4,opt,name=receivable_id,json=receivableId,proto3" json:"receivable_id,omitempty"` // deterministically derived from txid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxBodySend) Reset() {
	*x = TxBodySend{}
	mi := &file_proto_anos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxBodySend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxBodySend) ProtoMessage() {}

func (x *TxBodySend) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxBodySend.ProtoReflect.Descriptor instead.
func (*TxBodySend) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{4}
}

func (x *TxBodySend) GetTo() *AccountId {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *TxBodySend) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TxBodySend) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *TxBodySend) GetReceivableId() *Hash32 {
	if x != nil {
		return x.ReceivableId
	}
	return nil
}

type TxBodyReceive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceivableId  *Hash32                `protobuf:"bytes,1,opt,name=receivable_id,json=receivableId,proto3" json:"receivable_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxBodyReceive) Reset() {
	*x = TxBodyReceive{}
	mi := &file_proto_anos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxBodyReceive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxBodyReceive) ProtoMessage() {}

func (x *TxBodyReceive) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxBodyReceive.ProtoReflect.Descriptor instead.
func (*TxBodyReceive) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{5}
}

func (x *TxBodyReceive) GetReceivableId() *Hash32 {
	if x != nil {
		return x.ReceivableId
	}
	return nil
}

// Canonical bytes-to-sign for a transaction.
// Rule: signature = Ed25519( SHA256( serialize(TxSignable) ) )
type TxSignable struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Type    TxType                 `protobuf:"varint,1,opt,name=type,proto3,enum=anos.v2.TxType" json:"type,omitempty"`
	Account *AccountId             `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"` // the account chain being extended
	Prev    *Hash32                `protobuf:"bytes,3,opt,name=prev,proto3" json:"prev,omitempty"`       // previous tx hash (zero/empty means genesis head)
	Seq     uint64                 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`        // monotonic per-account sequence
	// Types that are valid to be assigned to Body:
	//
	//	*TxSignable_Send
	//	*TxSignable_Receive
	Body          isTxSignable_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxSignable) Reset() {
	*x = TxSignable{}
	mi := &file_proto_anos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxSignable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxSignable) ProtoMessage() {}

func (x *TxSignable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxSignable.ProtoReflect.Descriptor instead.
func (*TxSignable) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{6}
}

func (x *TxSignable) GetType() TxType {
	if x != nil {
		return x.Type
	}
	return TxType_TX_TYPE_UNSPECIFIED
}

func (x *TxSignable) GetAccount() *AccountId {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *TxSignable) GetPrev() *Hash32 {
	if x != nil {
		return x.Prev
	}
	return nil
}

func (x *TxSignable) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *TxSignable) GetBody() isTxSignable_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *TxSignable) GetSend() *TxBodySend {
	if x != nil {
		if x, ok := x.Body.(*TxSignable_Send); ok {
			return x.Send
		}
	}
	return nil
}

func (x *TxSignable) GetReceive() *TxBodyReceive {
	if x != nil {
		if x, ok := x.Body.(*TxSignable_Receive); ok {
			return x.Receive
		}
	}
	return nil
}

type isTxSignable_Body interface {
	isTxSignable_Body()
}

type TxSignable_Send struct {
	Send *TxBodySend `protobuf:"bytes,10,opt,name=send,proto3,oneof"`
}

type TxSignable_Receive struct {
	Receive *TxBodyReceive `protobuf:"bytes,11,opt,name=receive,proto3,oneof"`
}

func (*TxSignable_Send) isTxSignable_Body() {}

func (*TxSignable_Receive) isTxSignable_Body() {}

type Tx struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Type    TxType                 `protobuf:"varint,1,opt,name=type,proto3,enum=anos.v2.TxType" json:"type,omitempty"`
	Account *AccountId             `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"` // the account chain being extended
	Prev    *Hash32                `protobuf:"bytes,3,opt,name=prev,proto3" json:"prev,omitempty"`       // previous tx hash (zero/empty means genesis head)
	Seq     uint64                 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`        // monotonic per-account sequence
	// Types that are valid to be assigned to Body:
	//
	//	*Tx_Send
	//	*Tx_Receive
	Body          isTx_Body `protobuf_oneof:"body"`
	Sig           *Sig64    `protobuf:"bytes,20,opt,name=sig,proto3" json:"sig,omitempty"` // signature over TxSignable canonical bytes (see above)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tx) Reset() {
	*x = Tx{}
	mi := &file_proto_anos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tx) ProtoMessage() {}

func (x *Tx) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tx.ProtoReflect.Descriptor instead.
func (*Tx) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{7}
}

func (x *Tx) GetType() TxType {
	if x != nil {
		return x.Type
	}
	return TxType_TX_TYPE_UNSPECIFIED
}

func (x *Tx) GetAccount() *AccountId {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *Tx) GetPrev() *Hash32 {
	if x != nil {
		return x.Prev
	}
	return nil
}

func (x *Tx) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Tx) GetBody() isTx_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Tx) GetSend() *TxBodySend {
	if x != nil {
		if x, ok := x.Body.(*Tx_Send); ok {
			return x.Send
		}
	}
	return nil
}

func (x *Tx) GetReceive() *TxBodyReceive {
	if x != nil {
		if x, ok := x.Body.(*Tx_Receive); ok {
			return x.Receive
		}
	}
	return nil
}

func (x *Tx) GetSig() *Sig64 {
	if x != nil {
		return x.Sig
	}
	return nil
}

type isTx_Body interface {
	isTx_Body()
}

type Tx_Send struct {
	Send *TxBodySend `protobuf:"bytes,10,opt,name=send,proto3,oneof"`
}

type Tx_Receive struct {
	Receive *TxBodyReceive `protobuf:"bytes,11,opt,name=receive,proto3,oneof"`
}

func (*Tx_Send) isTx_Body() {}

func (*Tx_Receive) isTx_Body() {}

type Receivable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *Hash32                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	From          *AccountId             `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            *AccountId             `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Amount        uint64                 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Fee           uint64                 `protobuf:"varint,5,opt,name=fee,proto3" json:"fee,omitempty"`
	CreatedByTx   *Hash32                `protobuf:"bytes,6,opt,name=created_by_tx,json=createdByTx,proto3" json:"created_by_tx,omitempty"`
	Claimed       bool                   `protobuf:"varint,7,opt,name=claimed,proto3" json:"claimed,omitempty"`
	ClaimedByTx   *Hash32                `protobuf:"bytes,8,opt,name=claimed_by_tx,json=claimedByTx,proto3" json:"claimed_by_tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receivable) Reset() {
	*x = Receivable{}
	mi := &file_proto_anos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receivable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receivable) ProtoMessage() {}

func (x *Receivable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receivable.ProtoReflect.Descriptor instead.
func (*Receivable) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{8}
}

func (x *Receivable) GetId() *Hash32 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Receivable) GetFrom() *AccountId {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Receivable) GetTo() *AccountId {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Receivable) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Receivable) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *Receivable) GetCreatedByTx() *Hash32 {
	if x != nil {
		return x.CreatedByTx
	}
	return nil
}

func (x *Receivable) GetClaimed() bool {
	if x != nil {
		return x.Claimed
	}
	return false
}

func (x *Receivable) GetClaimedByTx() *Hash32 {
	if x != nil {
		return x.ClaimedByTx
	}
	return nil
}

type EpochRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	AcceptedTxs   []*Hash32              `protobuf:"bytes,2,rep,name=accepted_txs,json=acceptedTxs,proto3" json:"accepted_txs,omitempty"`
	StateRoot     *Hash32                `protobuf:"bytes,3,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	PrevEpochHash *Hash32                `protobuf:"bytes,4,opt,name=prev_epoch_hash,json=prevEpochHash,proto3" json:"prev_epoch_hash,omitempty"` // hash-chain epochs for audit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpochRecord) Reset() {
	*x = EpochRecord{}
	mi := &file_proto_anos_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpochRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochRecord) ProtoMessage() {}

func (x *EpochRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpochRecord.ProtoReflect.Descriptor instead.
func (*EpochRecord) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{9}
}

func (x *EpochRecord) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *EpochRecord) GetAcceptedTxs() []*Hash32 {
	if x != nil {
		return x.AcceptedTxs
	}
	return nil
}

func (x *EpochRecord) GetStateRoot() *Hash32 {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *EpochRecord) GetPrevEpochHash() *Hash32 {
	if x != nil {
		return x.PrevEpochHash
	}
	return nil
}

// Generic error for API responses.
type ApiError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // HTTP-ish or app-specific code (e.g., 400, 403, 500)
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // human-readable summary
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`   // optional extra info (stack, debug, etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiError) Reset() {
	*x = ApiError{}
	mi := &file_proto_anos_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiError) ProtoMessage() {}

func (x *ApiError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiError.ProtoReflect.Descriptor instead.
func (*ApiError) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{10}
}

func (x *ApiError) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ApiError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiError) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// /submit
type SubmitTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tx            *Tx                    `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTxRequest) Reset() {
	*x = SubmitTxRequest{}
	mi := &file_proto_anos_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTxRequest) ProtoMessage() {}

func (x *SubmitTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTxRequest.ProtoReflect.Descriptor instead.
func (*SubmitTxRequest) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{11}
}

func (x *SubmitTxRequest) GetTx() *Tx {
	if x != nil {
		return x.Tx
	}
	return nil
}

type SubmitTxResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ok    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// Optional: txid as computed by validators (or client) for display/debug.
	Txid *Hash32 `protobuf:"bytes,2,opt,name=txid,proto3" json:"txid,omitempty"`
	// If ok=false, error is set.
	Error         *ApiError `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTxResponse) Reset() {
	*x = SubmitTxResponse{}
	mi := &file_proto_anos_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTxResponse) ProtoMessage() {}

func (x *SubmitTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTxResponse.ProtoReflect.Descriptor instead.
func (*SubmitTxResponse) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{12}
}

func (x *SubmitTxResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SubmitTxResponse) GetTxid() *Hash32 {
	if x != nil {
		return x.Txid
	}
	return nil
}

func (x *SubmitTxResponse) GetError() *ApiError {
	if x != nil {
		return x.Error
	}
	return nil
}

// /account
type AccountState struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Account *AccountId             `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// Current head tx hash (zero/empty means genesis head)
	Head          *Hash32 `protobuf:"bytes,2,opt,name=head,proto3" json:"head,omitempty"`
	Balance       uint64  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Seq           uint64  `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountState) Reset() {
	*x = AccountState{}
	mi := &file_proto_anos_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountState) ProtoMessage() {}

func (x *AccountState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountState.ProtoReflect.Descriptor instead.
func (*AccountState) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{13}
}

func (x *AccountState) GetAccount() *AccountId {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *AccountState) GetHead() *Hash32 {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *AccountState) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *AccountState) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *AccountId             `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_proto_anos_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{14}
}

func (x *GetAccountRequest) GetAccount() *AccountId {
	if x != nil {
		return x.Account
	}
	return nil
}

type GetAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	State         *AccountState          `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Error         *ApiError              `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_proto_anos_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{15}
}

func (x *GetAccountResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GetAccountResponse) GetState() *AccountState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *GetAccountResponse) GetError() *ApiError {
	if x != nil {
		return x.Error
	}
	return nil
}

// /receivables
type ListReceivablesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Account        *AccountId             `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`                                      // list receivables destined to this account
	IncludeClaimed bool                   `protobuf:"varint,2,opt,name=include_claimed,json=includeClaimed,proto3" json:"include_claimed,omitempty"` // default false
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListReceivablesRequest) Reset() {
	*x = ListReceivablesRequest{}
	mi := &file_proto_anos_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReceivablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReceivablesRequest) ProtoMessage() {}

func (x *ListReceivablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReceivablesRequest.ProtoReflect.Descriptor instead.
func (*ListReceivablesRequest) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{16}
}

func (x *ListReceivablesRequest) GetAccount() *AccountId {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *ListReceivablesRequest) GetIncludeClaimed() bool {
	if x != nil {
		return x.IncludeClaimed
	}
	return false
}

type ListReceivablesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Receivables   []*Receivable          `protobuf:"bytes,2,rep,name=receivables,proto3" json:"receivables,omitempty"`
	Error         *ApiError              `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReceivablesResponse) Reset() {
	*x = ListReceivablesResponse{}
	mi := &file_proto_anos_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReceivablesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReceivablesResponse) ProtoMessage() {}

func (x *ListReceivablesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_anos_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReceivablesResponse.ProtoReflect.Descriptor instead.
func (*ListReceivablesResponse) Descriptor() ([]byte, []int) {
	return file_proto_anos_proto_rawDescGZIP(), []int{17}
}

func (x *ListReceivablesResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ListReceivablesResponse) GetReceivables() []*Receivable {
	if x != nil {
		return x.Receivables
	}
	return nil
}

func (x *ListReceivablesResponse) GetError() *ApiError {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_proto_anos_proto protoreflect.FileDescriptor

const file_proto_anos_proto_rawDesc = "" +
	"\n" +
	"\x10proto/anos.proto\x12\aanos.v2\"\x16\n" +
	"\x06Hash32\x12\f\n" +
	"\x01v\x18\x01 \x01(\fR\x01v\"\x15\n" +
	"\x05Sig64\x12\f\n" +
	"\x01v\x18\x01 \x01(\fR\x01v\"\x15\n" +
	"\x05Pub32\x12\f\n" +
	"\x01v\x18\x01 \x01(\fR\x01v\"\x19\n" +
	"\tAccountId\x12\f\n" +
	"\x01v\x18\x01 \x01(\fR\x01v\"\x90\x01\n" +
	"\n" +
	"TxBodySend\x12\"\n" +
	"\x02to\x18\x01 \x01(\v2\x12.anos.v2.AccountIdR\x02to\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x12\x10\n" +
	"\x03fee\x18\x03 \x01(\x04R\x03fee\x124\n" +
	"\rreceivable_id\x18\x04 \x01(\v2\x0f.anos.v2.Hash32R\freceivableId\"E\n" +
	"\rTxBodyReceive\x124\n" +
	"\rreceivable_id\x18\x01 \x01(\v2\x0f.anos.v2.Hash32R\freceivableId\"\xfd\x01\n" +
	"\n" +
	"TxSignable\x12#\n" +
	"\x04type\x18\x01 \x01(\x0e2\x0f.anos.v2.TxTypeR\x04type\x12,\n" +
	"\aaccount\x18\x02 \x01(\v2\x12.anos.v2.AccountIdR\aaccount\x12#\n" +
	"\x04prev\x18\x03 \x01(\v2\x0f.anos.v2.Hash32R\x04prev\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\x12)\n" +
	"\x04send\x18\n" +
	" \x01(\v2\x13.anos.v2.TxBodySendH\x00R\x04send\x122\n" +
	"\areceive\x18\v \x01(\v2\x16.anos.v2.TxBodyReceiveH\x00R\areceiveB\x06\n" +
	"\x04body\"\x97\x02\n" +
	"\x02Tx\x12#\n" +
	"\x04type\x18\x01 \x01(\x0e2\x0f.anos.v2.TxTypeR\x04type\x12,\n" +
	"\aaccount\x18\x02 \x01(\v2\x12.anos.v2.AccountIdR\aaccount\x12#\n" +
	"\x04prev\x18\x03 \x01(\v2\x0f.anos.v2.Hash32R\x04prev\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\x12)\n" +
	"\x04send\x18\n" +
	" \x01(\v2\x13.anos.v2.TxBodySendH\x00R\x04send\x122\n" +
	"\areceive\x18\v \x01(\v2\x16.anos.v2.TxBodyReceiveH\x00R\areceive\x12 \n" +
	"\x03sig\x18\x14 \x01(\v2\x0e.anos.v2.Sig64R\x03sigB\x06\n" +
	"\x04body\"\xa7\x02\n" +
	"\n" +
	"Receivable\x12\x1f\n" +
	"\x02id\x18\x01 \x01(\v2\x0f.anos.v2.Hash32R\x02id\x12&\n" +
	"\x04from\x18\x02 \x01(\v2\x12.anos.v2.AccountIdR\x04from\x12\"\n" +
	"\x02to\x18\x03 \x01(\v2\x12.anos.v2.AccountIdR\x02to\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x04R\x06amount\x12\x10\n" +
	"\x03fee\x18\x05 \x01(\x04R\x03fee\x123\n" +
	"\rcreated_by_tx\x18\x06 \x01(\v2\x0f.anos.v2.Hash32R\vcreatedByTx\x12\x18\n" +
	"\aclaimed\x18\a \x01(\bR\aclaimed\x123\n" +
	"\rclaimed_by_tx\x18\b \x01(\v2\x0f.anos.v2.Hash32R\vclaimedByTx\"\xc0\x01\n" +
	"\vEpochRecord\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x122\n" +
	"\faccepted_txs\x18\x02 \x03(\v2\x0f.anos.v2.Hash32R\vacceptedTxs\x12.\n" +
	"\n" +
	"state_root\x18\x03 \x01(\v2\x0f.anos.v2.Hash32R\tstateRoot\x127\n" +
	"\x0fprev_epoch_hash\x18\x04 \x01(\v2\x0f.anos.v2.Hash32R\rprevEpochHash\"P\n" +
	"\bApiError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\".\n" +
	"\x0fSubmitTxRequest\x12\x1b\n" +
	"\x02tx\x18\x01 \x01(\v2\v.anos.v2.TxR\x02tx\"p\n" +
	"\x10SubmitTxResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12#\n" +
	"\x04txid\x18\x02 \x01(\v2\x0f.anos.v2.Hash32R\x04txid\x12'\n" +
	"\x05error\x18\x03 \x01(\v2\x11.anos.v2.ApiErrorR\x05error\"\x8d\x01\n" +
	"\fAccountState\x12,\n" +
	"\aaccount\x18\x01 \x01(\v2\x12.anos.v2.AccountIdR\aaccount\x12#\n" +
	"\x04head\x18\x02 \x01(\v2\x0f.anos.v2.Hash32R\x04head\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x04R\abalance\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\"A\n" +
	"\x11GetAccountRequest\x12,\n" +
	"\aaccount\x18\x01 \x01(\v2\x12.anos.v2.AccountIdR\aaccount\"z\n" +
	"\x12GetAccountResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12+\n" +
	"\x05state\x18\x02 \x01(\v2\x15.anos.v2.AccountStateR\x05state\x12'\n" +
	"\x05error\x18\x03 \x01(\v2\x11.anos.v2.ApiErrorR\x05error\"o\n" +
	"\x16ListReceivablesRequest\x12,\n" +
	"\aaccount\x18\x01 \x01(\v2\x12.anos.v2.AccountIdR\aaccount\x12'\n" +
	"\x0finclude_claimed\x18\x02 \x01(\bR\x0eincludeClaimed\"\x89\x01\n" +
	"\x17ListReceivablesResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x125\n" +
	"\vreceivables\x18\x02 \x03(\v2\x13.anos.v2.ReceivableR\vreceivables\x12'\n" +
	"\x05error\x18\x03 \x01(\v2\x11.anos.v2.ApiErrorR\x05error*H\n" +
	"\x06TxType\x12\x17\n" +
	"\x13TX_TYPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fTX_TYPE_SEND\x10\x01\x12\x13\n" +
	"\x0fTX_TYPE_RECEIVE\x10\x02B\x18Z\x16anos/internal/proto;pbb\x06proto3"

var (
	file_proto_anos_proto_rawDescOnce sync.Once
	file_proto_anos_proto_rawDescData []byte
)

func file_proto_anos_proto_rawDescGZIP() []byte {
	file_proto_anos_proto_rawDescOnce.Do(func() {
		file_proto_anos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_anos_proto_rawDesc), len(file_proto_anos_proto_rawDesc)))
	})
	return file_proto_anos_proto_rawDescData
}

var file_proto_anos_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_anos_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_anos_proto_goTypes = []any{
	(TxType)(0),                     // 0: anos.v2.TxType
	(*Hash32)(nil),                  // 1: anos.v2.Hash32
	(*Sig64)(nil),                   // 2: anos.v2.Sig64
	(*Pub32)(nil),                   // 3: anos.v2.Pub32
	(*AccountId)(nil),               // 4: anos.v2.AccountId
	(*TxBodySend)(nil),              // 5: anos.v2.TxBodySend
	(*TxBodyReceive)(nil),           // 6: anos.v2.TxBodyReceive
	(*TxSignable)(nil),              // 7: anos.v2.TxSignable
	(*Tx)(nil),                      // 8: anos.v2.Tx
	(*Receivable)(nil),              // 9: anos.v2.Receivable
	(*EpochRecord)(nil),             // 10: anos.v2.EpochRecord
	(*ApiError)(nil),                // 11: anos.v2.ApiError
	(*SubmitTxRequest)(nil),         // 12: anos.v2.SubmitTxRequest
	(*SubmitTxResponse)(nil),        // 13: anos.v2.SubmitTxResponse
	(*AccountState)(nil),            // 14: anos.v2.AccountState
	(*GetAccountRequest)(nil),       // 15: anos.v2.GetAccountRequest
	(*GetAccountResponse)(nil),      // 16: anos.v2.GetAccountResponse
	(*ListReceivablesRequest)(nil),  // 17: anos.v2.ListReceivablesRequest
	(*ListReceivablesResponse)(nil), // 18: anos.v2.ListReceivablesResponse
}
var file_proto_anos_proto_depIdxs = []int32{
	4,  // 0: anos.v2.TxBodySend.to:type_name -> anos.v2.AccountId
	1,  // 1: anos.v2.TxBodySend.receivable_id:type_name -> anos.v2.Hash32
	1,  // 2: anos.v2.TxBodyReceive.receivable_id:type_name -> anos.v2.Hash32
	0,  // 3: anos.v2.TxSignable.type:type_name -> anos.v2.TxType
	4,  // 4: anos.v2.TxSignable.account:type_name -> anos.v2.AccountId
	1,  // 5: anos.v2.TxSignable.prev:type_name -> anos.v2.Hash32
	5,  // 6: anos.v2.TxSignable.send:type_name -> anos.v2.TxBodySend
	6,  // 7: anos.v2.TxSignable.receive:type_name -> anos.v2.TxBodyReceive
	0,  // 8: anos.v2.Tx.type:type_name -> anos.v2.TxType
	4,  // 9: anos.v2.Tx.account:type_name -> anos.v2.AccountId
	1,  // 10: anos.v2.Tx.prev:type_name -> anos.v2.Hash32
	5,  // 11: anos.v2.Tx.send:type_name -> anos.v2.TxBodySend
	6,  // 12: anos.v2.Tx.receive:type_name -> anos.v2.TxBodyReceive
	2,  // 13: anos.v2.Tx.sig:type_name -> anos.v2.Sig64
	1,  // 14: anos.v2.Receivable.id:type_name -> anos.v2.Hash32
	4,  // 15: anos.v2.Receivable.from:type_name -> anos.v2.AccountId
	4,  // 16: anos.v2.Receivable.to:type_name -> anos.v2.AccountId
	1,  // 17: anos.v2.Receivable.created_by_tx:type_name -> anos.v2.Hash32
	1,  // 18: anos.v2.Receivable.claimed_by_tx:type_name -> anos.v2.Hash32
	1,  // 19: anos.v2.EpochRecord.accepted_txs:type_name -> anos.v2.Hash32
	1,  // 20: anos.v2.EpochRecord.state_root:type_name -> anos.v2.Hash32
	1,  // 21: anos.v2.EpochRecord.prev_epoch_hash:type_name -> anos.v2.Hash32
	8,  // 22: anos.v2.SubmitTxRequest.tx:type_name -> anos.v2.Tx
	1,  // 23: anos.v2.SubmitTxResponse.txid:type_name -> anos.v2.Hash32
	11, // 24: anos.v2.SubmitTxResponse.error:type_name -> anos.v2.ApiError
	4,  // 25: anos.v2.AccountState.account:type_name -> anos.v2.AccountId
	1,  // 26: anos.v2.AccountState.head:type_name -> anos.v2.Hash32
	4,  // 27: anos.v2.GetAccountRequest.account:type_name -> anos.v2.AccountId
	14, // 28: anos.v2.GetAccountResponse.state:type_name -> anos.v2.AccountState
	11, // 29: anos.v2.GetAccountResponse.error:type_name -> anos.v2.ApiError
	4,  // 30: anos.v2.ListReceivablesRequest.account:type_name -> anos.v2.AccountId
	9,  // 31: anos.v2.ListReceivablesResponse.receivables:type_name -> anos.v2.Receivable
	11, // 32: anos.v2.ListReceivablesResponse.error:type_name -> anos.v2.ApiError
	33, // [33:33] is the sub-list for method output_type
	33, // [33:33] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_proto_anos_proto_init() }
func file_proto_anos_proto_init() {
	if File_proto_anos_proto != nil {
		return
	}
	file_proto_anos_proto_msgTypes[6].OneofWrappers = []any{
		(*TxSignable_Send)(nil),
		(*TxSignable_Receive)(nil),
	}
	file_proto_anos_proto_msgTypes[7].OneofWrappers = []any{
		(*Tx_Send)(nil),
		(*Tx_Receive)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_anos_proto_rawDesc), len(file_proto_anos_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_anos_proto_goTypes,
		DependencyIndexes: file_proto_anos_proto_depIdxs,
		EnumInfos:         file_proto_anos_proto_enumTypes,
		MessageInfos:      file_proto_anos_proto_msgTypes,
	}.Build()
	File_proto_anos_proto = out.File
	file_proto_anos_proto_goTypes = nil
	file_proto_anos_proto_depIdxs = nil
}
